name: NodeJS with Webpack

on:
  push:
    branches: [ master ]
    inputs:
      service:
        description: 'Number of Octocats'
        required: true    
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest    
    steps:
    - name: Build
      run: 
        npm install
        