name: NodeJS with Webpack

on:
  push:
    branches: [ master ]
    input:

  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    
    
    steps:
    - name: Build
      run: |
        npm install
      
