name: NodeJS with Webpack

on:
  push:
    branches: [ master ]
    
  pull_request:
    branches: [ master ]
inputs:
  service:
    description: 'Number of Octocats'
    required: true
jobs:
  build:
    runs-on: ubuntu-latest    
    steps:
    - name: Build
      run: 
        npm install
        
